wandb_version: 1

architecture:
  desc: null
  value: DistilBERT
dataset:
  desc: null
  value: MRPC
learning_rate:
  desc: null
  value: 6.704e-06
adam_epsilon:
  desc: null
  value: 1.0e-08
warmup_steps:
  desc: null
  value: 70
weight_decay:
  desc: null
  value: 0.0
train_batch_size:
  desc: null
  value: 4
eval_batch_size:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.35.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700069532.140341
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 51
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 51
      - 53
      - 55
      - 103
      3:
      - 2
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      6: 4.35.1
      8:
      - 3
      - 5
      13: windows-amd64
